/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AppDay {
    'day': number;
  }
  interface AppHome {}
  interface AppMonth {
    'firstMonday': number;
  }
  interface AppMonthYear {}
  interface AppRoot {}
  interface AppWeek {
    'firstDay': number;
  }
}

declare global {


  interface HTMLAppDayElement extends Components.AppDay, HTMLStencilElement {}
  var HTMLAppDayElement: {
    prototype: HTMLAppDayElement;
    new (): HTMLAppDayElement;
  };

  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppMonthElement extends Components.AppMonth, HTMLStencilElement {}
  var HTMLAppMonthElement: {
    prototype: HTMLAppMonthElement;
    new (): HTMLAppMonthElement;
  };

  interface HTMLAppMonthYearElement extends Components.AppMonthYear, HTMLStencilElement {}
  var HTMLAppMonthYearElement: {
    prototype: HTMLAppMonthYearElement;
    new (): HTMLAppMonthYearElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLAppWeekElement extends Components.AppWeek, HTMLStencilElement {}
  var HTMLAppWeekElement: {
    prototype: HTMLAppWeekElement;
    new (): HTMLAppWeekElement;
  };
  interface HTMLElementTagNameMap {
    'app-day': HTMLAppDayElement;
    'app-home': HTMLAppHomeElement;
    'app-month': HTMLAppMonthElement;
    'app-month-year': HTMLAppMonthYearElement;
    'app-root': HTMLAppRootElement;
    'app-week': HTMLAppWeekElement;
  }
}

declare namespace LocalJSX {
  interface AppDay {
    'day'?: number;
  }
  interface AppHome {}
  interface AppMonth {
    'firstMonday'?: number;
  }
  interface AppMonthYear {}
  interface AppRoot {}
  interface AppWeek {
    'firstDay'?: number;
  }

  interface IntrinsicElements {
    'app-day': AppDay;
    'app-home': AppHome;
    'app-month': AppMonth;
    'app-month-year': AppMonthYear;
    'app-root': AppRoot;
    'app-week': AppWeek;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'app-day': LocalJSX.AppDay & JSXBase.HTMLAttributes<HTMLAppDayElement>;
      'app-home': LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
      'app-month': LocalJSX.AppMonth & JSXBase.HTMLAttributes<HTMLAppMonthElement>;
      'app-month-year': LocalJSX.AppMonthYear & JSXBase.HTMLAttributes<HTMLAppMonthYearElement>;
      'app-root': LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
      'app-week': LocalJSX.AppWeek & JSXBase.HTMLAttributes<HTMLAppWeekElement>;
    }
  }
}


